name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    # steps:
    # - uses: actions/checkout@v3
    # - name: Build
    #   run: cargo build --verbose
    # - name: Run tests
    #   run: cargo test --verbose
  steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cd my_rust_project  
        cargo build --verbose
    - name: Run tests
      run: |
        cd my_rust_project  
        cargo test --verbose


    # steps:
    # - uses: actions/checkout@v3
    # - name: Navigate to project directory
    #   run: cd my_rust_project
    # - name: Build
    #   run: cargo build --verbose
    # - name: Run tests
    #   run: cargo test --verbose